-- Create the COND_DWM_CALC table
create table FIA.COND_DWM_CALC(
	CN varchar(34),
	STATECD numeric(4,0),
	COUNTYCD numeric(3,0),
	PLOT real,
	MEASYEAR numeric(4,0),
	INVYR numeric(4,0),
	CONDID numeric(1,0),
	EVALID numeric(6,0),
	PLT_CN varchar(34),
	CND_CN varchar(34),
	STRATUM_CN varchar(34),
	PHASE varchar(3),
	CONDPROP_CWD numeric(13,12),
	CONDPROP_FWD_SM numeric(13,12),
	CONDPROP_FWD_MD numeric(13,12),
	CONDPROP_FWD_LG numeric(13,12),
	CONDPROP_DUFF numeric(13,12),
	CWD_TL_COND numeric(13,10),
	CWD_TL_UNADJ numeric(13,10),
	CWD_TL_ADJ numeric(13,10),
	CWD_LPA_COND double precision,
	CWD_LPA_UNADJ double precision,
	CWD_LPA_ADJ double precision,
	CWD_VOLCF_COND double precision,
	CWD_VOLCF_UNADJ double precision,
	CWD_VOLCF_ADJ double precision,
	CWD_DRYBIO_COND double precision,
	CWD_DRYBIO_UNADJ double precision,
	CWD_DRYBIO_ADJ double precision,
	CWD_CARBON_COND double precision,
	CWD_CARBON_UNADJ double precision,
	CWD_CARBON_ADJ double precision,
	FWD_SM_TL_COND numeric(13,10),
	FWD_SM_TL_UNADJ numeric(13,10),
	FWD_SM_TL_ADJ numeric(13,10),
	FWD_SM_CNT_COND integer,
	FWD_SM_VOLCF_COND double precision,
	FWD_SM_VOLCF_UNADJ double precision,
	FWD_SM_VOLCF_ADJ double precision,
	FWD_SM_DRYBIO_COND double precision,
	FWD_SM_DRYBIO_UNADJ double precision,
	FWD_SM_DRYBIO_ADJ double precision,
	FWD_SM_CARBON_COND double precision,
	FWD_SM_CARBON_UNADJ double precision,
	FWD_SM_CARBON_ADJ double precision,
	FWD_MD_TL_COND numeric(13,10),
	FWD_MD_TL_UNADJ numeric(13,10),
	FWD_MD_TL_ADJ numeric(13,10),
	FWD_MD_CNT_COND integer,
	FWD_MD_VOLCF_COND double precision,
	FWD_MD_VOLCF_UNADJ double precision,
	FWD_MD_VOLCF_ADJ double precision,
	FWD_MD_DRYBIO_COND double precision,
	FWD_MD_DRYBIO_UNADJ double precision,
	FWD_MD_DRYBIO_ADJ double precision,
	FWD_MD_CARBON_COND double precision,
	FWD_MD_CARBON_UNADJ double precision,
	FWD_MD_CARBON_ADJ double precision,
	FWD_LG_TL_COND numeric(13,10),
	FWD_LG_TL_UNADJ numeric(13,10),
	FWD_LG_TL_ADJ numeric(13,10),
	FWD_LG_CNT_COND integer,
	FWD_LG_VOLCF_COND double precision,
	FWD_LG_VOLCF_UNADJ double precision,
	FWD_LG_VOLCF_ADJ double precision,
	FWD_LG_DRYBIO_COND double precision,
	FWD_LG_DRYBIO_UNADJ double precision,
	FWD_LG_DRYBIO_ADJ double precision,
	FWD_LG_CARBON_COND double precision,
	FWD_LG_CARBON_UNADJ double precision,
	FWD_LG_CARBON_ADJ double precision,
	PILE_SAMPLE_AREA_COND numeric(13,12),
	PILE_SAMPLE_AREA_UNADJ numeric(13,12),
	PILE_SAMPLE_AREA_ADJ numeric(13,12),
	PILE_VOLCF_COND double precision,
	PILE_VOLCF_UNADJ double precision,
	PILE_VOLCF_ADJ double precision,
	PILE_DRYBIO_COND double precision,
	PILE_DRYBIO_UNADJ double precision,
	PILE_DRYBIO_ADJ double precision,
	PILE_CARBON_COND double precision,
	PILE_CARBON_UNADJ double precision,
	PILE_CARBON_ADJ double precision,
	FUEL_DEPTH double precision,
	FUEL_BIOMASS double precision, -- empty
	FUEL_CARBON double precision, -- empty
	DUFF_DEPTH double precision,
	DUFF_BIOMASS double precision,
	DUFF_CARBON double precision,
	LITTER_DEPTH double precision,
	LITTER_BIOMASS double precision,
	LITTER_CARBON double precision,
	DUFF_TC_COND numeric(14,12),
	DUFF_TC_UNADJ numeric(14,12),
	DUFF_TC_ADJ numeric(14,12),
	AVG_WOOD_DENSITY numeric(12,10),	
	CREATED_BY varchar(30),
	CREATED_DATE date,
	CREATED_IN_INSTANCE varchar(6),
	MODIFIED_BY varchar(30),
	MODIFIED_DATE date,
	MODIFIED_IN_INSTANCE varchar(6),
	CYCLE numeric(2,0),
	SUBCYCLE numeric(2,0),
	UNITCD numeric(2,0),
	RSCD numeric(2,0)
	);