-- Create the DWM_FINE_WOODY_DEBRIS table
create table FIA.DWM_FINE_WOODY_DEBRIS(
	CN varchar(34),
	PLT_CN varchar(34),
	INVYR numeric(4,0),
	STATECD	numeric(4,0),
	COUNTYCD numeric(3,0),
	PLOT numeric(5,0),
	TRANSECT numeric(3,0),
	SUBP numeric(1,0),
	CONDID numeric(1,0),
	MEASYEAR numeric(4,0),
	SMALLCT numeric(3,0),
	MEDIUMCT numeric(3,0),
	LARGECT numeric(3,0),
	RSNCTCD numeric(1,0),
	PILESCD numeric(1,0),
	SMALL_TL_COND double precision,
	SMALL_TL_PLOT double precision,
	SMALL_TL_UNADJ double precision,
	MEDIUM_TL_COND double precision,
	MEDIUM_TL_PLOT double precision,
	MEDIUM_TL_UNADJ double precision,
	LARGE_TL_COND double precision,
	LARGE_TL_PLOT double precision,
	LARGE_TL_UNADJ double precision,
	CREATED_BY varchar(30),
	CREATED_DATE date,
	CREATED_IN_INSTANCE varchar(6),
	MODIFIED_BY varchar(30),
	MODIFIED_DATE date,
	MODIFIED_IN_INSTANCE varchar(6),
	FWD_STATUS_CD numeric(1,0),
	FWD_NONSAMPLE_REASN_CD numeric(2,0),
	FWD_SAMPLE_METHOD varchar(6),
	UNIQUE(PLT_CN,TRANSECT,SUBP,CONDID),PRIMARY KEY(CN)
);