-- Create the DWM_COARSE_WOODY_DEBRIS table
create table FIA.DWM_COARSE_WOODY_DEBRIS(
	CN varchar(34),
	PLT_CN varchar(34),
	INVYR numeric(4,0),
	STATECD	numeric(4,0),
	COUNTYCD numeric(3,0),
	PLOT numeric(5,0),
	SUBP numeric(1,0),
	TRANSECT numeric(3,0),
	CWDID real,
	MEASYEAR numeric(4,0),
	CONDID numeric(1,0),
	SLOPDIST double precision,
	HORIZ_DIST double precision,
	SPCD double precision,
	DECAYCD numeric(1,0),
	TRANSDIA numeric(3,0),
	SMALLDIA numeric(3,0),
	LARGEDIA numeric(3,0),
	LENGTH numeric(3,0),
	HOLLOWCD varchar(1), -- Y/N
	CWDHSTCD numeric(1,0),
	VOLCF double precision,
	DRYBIO double precision,
	CARBON double precision,
	COVER_PCT double precision,
	LPA_UNADJ double precision,
	LPA_PLOT double precision,
	LPA_COND double precision,
	LPA_UNADJ_RGN double precision,
	LPA_PLOT_RGN double precision,
	LPA_COND_RGN double precision,
	COVER_PCT_RGN double precision,
	CHARRED_CD numeric(1,0), -- misc codes
	ORNTCD_PNWRS varchar(1), -- misc codes
	CREATED_BY varchar(30),
	CREATED_DATE date,
	CREATED_IN_INSTANCE varchar(6),
	MODIFIED_BY varchar(30),
	MODIFIED_DATE date,
	MODIFIED_IN_INSTANCE varchar(6),
	CWD_SAMPLE_METHOD varchar(6),
	HOLLOW_DIA numeric(3,0),
	HORIZ_DIST_CD numeric(1,0),
	INCLINATION numeric(2,0),
	LARGE_END_DIA_CLASS numeric(1,0),
	LENGTH_CD numeric(1,0),
	UNIQUE(PLT_CN,TRANSECT,SUBP,CWDID), PRIMARY KEY(CN)
);