-- Create the LICHEN_VISIT table
create table FIA.LICHEN_VISIT(
	CN varchar(34),
	PLT_CN varchar(34),
	INVYR numeric(4,0),
	STATECD	numeric(4,0),
	COUNTYCD numeric(3,0),
	PLOT numeric(5,0),
	MEASDAY numeric(2,0),
	MEASMON numeric(2,0),
	MEASYEAR numeric(4,0),
	LICHEN_STATCD numeric(2,0),
	LIPROJCD numeric(2,0),
	SMPLSTRT numeric(4,0),
	SMPLSTP numeric(4,0),
	SMPLTIME numeric(4,0),
	SFTWDPCT numeric(3,0),
	HRDWDPCT numeric(3,0),
	SHRUBPCT numeric(3,0),
	GAPPCT numeric(3,0),
	GAPRCNT numeric(2,0),
	TALLSHRB numeric(2,0),
	FTRCD1 smallint,
	FTRCD2 smallint,
	FTRCD3 smallint,
	FTRCD4 smallint,
	ISSUECD1 smallint,
	ISSUECD2 smallint,
	ISSUECD3 smallint,
	ISSUECD4 smallint,
	SZCLSCD1 numeric(2,0),
	SZCLSCD2 numeric(2,0),
	SZCLSCD3 numeric(2,0),
	CREATED_BY varchar(30),
	CREATED_DATE date,
	CREATED_IN_INSTANCE varchar(6),
	MODIFIED_BY varchar(30),
	MODIFIED_DATE date,
	MODIFIED_IN_INSTANCE varchar(6),
	PRIMARY KEY (CN), UNIQUE(PLT_CN)
);