-- Create the OZONE_VISIT table
create table FIA.OZONE_VISIT(
	CN varchar(34),
	PLT_CN varchar(34),
	INVYR numeric(4,0),
	STATECD	numeric(4,0),
	COUNTYCD numeric(3,0),
	O3PLOT integer,
	FIELD_ID numeric(7,0),
	SPLIT_PLOTID numeric(1,0),
	SMPKNDCD numeric(2,0),
	MEASDAY numeric(2,0),
	MEASMON numeric(2,0),
	MEASYEAR numeric(4,0),
	PLTSIZE smallint,
	ASPECT numeric(3,0),
	TERRPOS smallint,
	SOILDPTH smallint,
	SOILDRN smallint,
	PLTDSTRB smallint,
	CRWTYPCD numeric(1,0),
	PLOTWET smallint,
	INJCHECK numeric(2,0),
	GRIDDEN numeric(1,0),
	CREATED_BY varchar(20),
	CREATED_DATE date,
	CREATED_IN_INSTANCE varchar(6),
	MODIFIED_BY varchar(20),
	MODIFIED_DATE date,
	MODIFIED_IN_INSTANCE varchar(6),
	PRIMARY KEY (CN), UNIQUE (PLT_CN)
);