-- Create the OZONE_PLOT_SUMMARY table
create table FIA.OZONE_PLOT_SUMMARY(
	CN varchar(34),
	INVYR numeric(4,0),
	STATECD	numeric(4,0),
	COUNTYCD numeric(3,0),
	O3PLOT integer,
	FIELD_ID numeric(7,0),
	SPLIT_PLOTID numeric(1,0),
	MEASYEAR numeric(4,0),
	SPECIES_EVAL_CNT smallint,
	BIOSITE_INDEX double precision,
	ELEV numeric(5,0),
	PLTSIZE smallint,
	ASPECT numeric(3,0),
	TERRPOS smallint,
	SOILDPTH smallint,
	SOILDRN smallint,
	PLOTWET smallint,
	PLTDSTRB smallint,
	BIOSITE_INDEX_MULTIPLIER double precision,
	LAT numeric(8,6),
	LON	numeric(9,6),
	CREATED_BY varchar(20),
	CREATED_DATE date,
	CREATED_IN_INSTANCE varchar(6),
	MODIFIED_BY varchar(20),
	MODIFIED_DATE date,
	MODIFIED_IN_INSTANCE varchar(6),
	PRIMARY KEY (CN), UNIQUE(STATECD,INVYR,COUNTYCD,O3PLOT,FIELD_ID,SPLIT_PLOTID)
);