-- Create the OZONE_SPECIES_SUMMARY table
create table FIA.OZONE_SPECIES_SUMMARY(
	CN varchar(34),
	INVYR numeric(4,0),
	STATECD numeric(4,0),
	COUNTYCD numeric(3,0),
	O3PLOT integer,
	FIELD_ID numeric(7,0),
	SPLIT_PLOTID numeric(1,0),
	GROUND_LOC_CD numeric(1,0),
	MEASYEAR numeric(4,0),
	BIOSPCD smallint,
	AMNT_MAX double precision,
	AMNT_MIN double precision,
	AMNT_MEAN double precision,
	SVRTY_MAX double precision,
	SVRTY_MIN double precision,
	SVRTY_MEAN double precision,
	PLANT_INJ_CNT smallint,
	PLANT_EVAL_CNT smallint,
	PLANT_RATIO double precision,
	BIOSPCD_SUM double precision,
	BIOSPCD_INDEX double precision,
	ELEV numeric(5,0),
	PLTSIZE smallint,
	ASPECT numeric(3,0),
	TERRPOS smallint,
	SOILDPTH smallint,
	SOILDRN smallint,
	PLOTWET smallint,
	PLTDSTRB smallint,
	CREATED_BY varchar(30),
	CREATED_DATE date,
	CREATED_IN_INSTANCE varchar(6),
	MODIFIED_BY varchar(30),
	MODIFIED_DATE date,
	MODIFIED_IN_INSTANCE varchar(6)
);