-- Create the OZONE_PLOT table
create table FIA.OZONE_PLOT(
	CN varchar(34),
	SRV_CN varchar(34),
	CTY_CN varchar(34),
	INVYR numeric(4,0),
	STATECD	numeric(4,0),
	UNITCD numeric(2,0),
	COUNTYCD numeric(3,0),
	O3PLOT integer,
	FIELD_ID numeric(7,0),
	SPLIT_PLOTID numeric(1,0),
	MEASYEAR numeric(4,0),
	MEASMON	numeric(2,0),
	MEASDAY	numeric(2,0),
	LAT numeric(8,6),
	LON numeric(9,6),
	ELEVATION integer,
	MANUAL numeric(3,1),
	QA_STATUS numeric(1,0),
	CREATED_BY varchar(20),
	CREATED_DATE date,
	CREATED_IN_INSTANCE varchar(6),
	MODIFIED_BY varchar(20),
	MODIFIED_DATE date,
	MODIFIED_IN_INSTANCE varchar(6),
	CYCLE numeric(2,0),
	SUBCYCLE numeric(2,0),
	PRIMARY KEY(CN), UNIQUE(STATECD,INVYR,COUNTYCD,O3PLOT,FIELD_ID,SPLIT_PLOTID)
);