-- Create the OZONE_BIOSITE_SUMMARY table
create table FIA.OZONE_BIOSITE_SUMMARY(
	CN varchar(34),
	INVYR numeric(4,0),
	STATECD	numeric(4,0),
	COUNTYCD numeric(3,0),
	O3PLOT integer,
	FIELD_ID numeric(7,0),
	LOCATION_CNT smallint,
	GROUND_LOC_CD numeric(1,0),
	MEASYEAR numeric(4,0),
	PLANT_INJ_CNT smallint,
	PLANT_EVAL_CNT smallint,
	PLANT_RATIO double precision,
	SPECIES_EVAL_CNT smallint,
	BIOSITE_INDEX double precision,
	BIOSITE_INDEX_MULTIPLIER double precision,
	SVRTY_CLASS_ZERO smallint,
	SVRTY_CLASS_ONE smallint,
	SVRTY_CLASS_TWO smallint,
	SVRTY_CLASS_THREE smallint,
	SVRTY_CLASS_FOUR smallint,
	SVRTY_CLASS_FIVE smallint,
	CREATED_BY varchar(20),
	CREATED_DATE date,
	CREATED_IN_INSTANCE varchar(6),
	MODIFIED_BY varchar(20),
	MODIFIED_DATE date,
	MODIFIED_IN_INSTANCE varchar(6),
	PRIMARY KEY(CN), UNIQUE(STATECD,INVYR,COUNTYCD,O3PLOT,FIELD_ID)
);