-- Create the PLOT table
create table FIA.PLOT(
	CN varchar(34),
	SRV_CN varchar(34),
	CTY_CN varchar(34),
	PREV_PLT_CN varchar(34), -- just in case, better to have 15 than 14.
	INVYR numeric(4,0),
	STATECD	numeric(4,0),
	UNITCD numeric(2,0),
	COUNTYCD numeric(3,0),
	PLOT numeric(5,0),
	PLOT_STATUS_CD numeric(1,0),
	PLOT_NONSAMPLE_REASN_CD numeric(2,0),
	MEASYEAR numeric(4,0),
	MEASMON numeric(2,0),
	MEASDAY numeric(2,0),
	REMPER numeric(3,1),
	KINDCD numeric(2,0),
	DESIGNCD numeric(4,0),
	RDDISTCD numeric(2,0),
	WATERCD numeric(2,0),
	LAT numeric(8,6),
	LON numeric(9,6),
	ELEV numeric(5,0),
	GROW_TYP_CD numeric(2,0),
	MORT_TYP_CD numeric(2,0),
	P2PANEL numeric(2,0),
	P3PANEL numeric(2,0),
	ECOSUBCD varchar(7), -- bad one " 231Ca"
	CONGCD numeric(4,0),
	MANUAL numeric(3,1),
	SUBPANEL numeric(2,0),
	KINDCD_NC numeric(2,0),
	QA_STATUS numeric(1,0),
	CREATED_BY varchar(30),
	CREATED_DATE date,
	CREATED_IN_INSTANCE varchar(6),
	MODIFIED_BY varchar(30),
	MODIFIED_DATE date,
	MODIFIED_IN_INSTANCE varchar(6),
	MICROPLOT_LOC varchar(12),
	DECLINATION numeric(4,1),
	EMAP_HEX numeric(7,0),
	SAMP_METHOD_CD numeric(1,0),
	SUBP_EXAMINE_CD numeric(1,0),
	MACRO_BREAKPOINT_DIA numeric(2,0),
	INTENSITY varchar(3),
	CYCLE numeric(2,0),
	SUBCYCLE numeric(2,0),
	ECO_UNIT_PNW varchar(10),
	TOPO_POSITION_PNW varchar(2),
	NF_SAMPLING_STATUS_CD numeric(1,0),
	NF_PLOT_STATUS_CD numeric(1,0),
	NF_PLOT_NONSAMPLE_REASN_CD numeric(2,0),
	P2VEG_SAMPLING_STATUS_CD numeric(1,0),
	P2VEG_SAMPLING_LEVEL_DETAIL_CD numeric(1,0),
	INVASIVE_SAMPLING_STATUS_CD numeric(1,0),
	INVASIVE_SPECIMEN_RULE_CD numeric(1,0),
	DESIGNCD_P2A numeric(4,0),
	PRIMARY KEY (CN),
	UNIQUE(STATECD, INVYR, UNITCD, COUNTYCD, PLOT)
);