-- Create the POP_STRATUM table
create table FIA.POP_STRATUM(
	CN varchar(34),
	ESTN_UNIT_CN varchar(34),
	RSCD numeric(2,0),
	EVALID numeric(6,0), 
	ESTN_UNIT numeric(6,0),
	STRATUMCD numeric(6,0),
	STRATUM_DESCR varchar(255),
	STATECD numeric(4,0),
	P1POINTCNT numeric(12,0),
	P2POINTCNT numeric(12,0),
	EXPNS double precision,
	ADJ_FACTOR_MACR double precision,
	ADJ_FACTOR_SUBP double precision,
	ADJ_FACTOR_MICR double precision,
	ADJ_FACTOR_CWD double precision,
	ADJ_FACTOR_FWD_SM double precision,	
	ADJ_FACTOR_FWD_LG double precision,
	ADJ_FACTOR_DUFF	double precision,
	CREATED_BY varchar(30),
	CREATED_DATE date,
	CREATED_IN_INSTANCE varchar(6),
	MODIFIED_BY varchar(30),
	MODIFIED_DATE date,
	MODIFIED_IN_INSTANCE varchar(6),
	PRIMARY KEY (CN),
	UNIQUE(RSCD, EVALID, ESTN_UNIT, STRATUMCD)
);