-- Create the SEEDLING_REGEN table
create table FIA.SEEDLING_REGEN(
	CN varchar(34),
	PLT_CN varchar(34),
	CND_CN varchar(34),
	SCD_CN varchar(34),
	INVYR numeric(4,0),
	STATECD numeric(4,0),
	UNITCD numeric(2,0),
	COUNTYCD numeric(3,0),
	PLOT numeric(5,0),
	SUBP numeric(1,0),
	CONDID numeric(1,0),
	SPCD smallint,
	SPGRPCD numeric(2,0),
	SEEDLING_SOURCE_CD varchar(2),
	LENGTH_CLASS_CD numeric(1,0),
	SEEDLINGCOUNT numeric(3,0),
	CREATED_BY varchar(30),
	CREATED_DATE date,
	CREATED_IN_INSTANCE varchar(6),
	MODIFIED_BY varchar(30),
	MODIFIED_DATE date,
	MODIFIED_IN_INSTANCE varchar(6),
	CYCLE numeric(2,0),
	SUBCYCLE numeric(2,0),
	PRIMARY KEY (CN),
	UNIQUE(STATECD, COUNTYCD, PLOT, SUBP, INVYR, SPCD, CONDID, SEEDLING_SOURCE_CD, LENGTH_CLASS_CD)
);