-- Create the SITETREE table
create table FIA.SITETREE(
	CN varchar(34),
	PLT_CN varchar(34),
	PREV_SIT_CN varchar(34),
	INVYR numeric(4,0),
	STATECD numeric(4,0),
	UNITCD numeric(2,0),
	COUNTYCD numeric(3,0),
	PLOT numeric(5,0),
	CONDID numeric(1,0),
	TREE numeric(9,0),
	SPCD smallint,
	DIA numeric(5,2),
	HT numeric(3,0),
	AGEDIA numeric(3,0),
	SPGRPCD numeric(2,0),
	SITREE numeric(3,0),
	SIBASE numeric(3,0),
	SUBP numeric(3,0),
	AZIMUTH numeric(3,0),
	DIST numeric(4,1),
	METHOD numeric(2,0),
	SITREE_EST numeric(3,0),
	VALIDCD numeric(1,0),
	CREATED_BY varchar(30),
	CREATED_DATE date,
	CREATED_IN_INSTANCE varchar(6),
	MODIFIED_BY varchar(30),
	MODIFIED_DATE date,
	MODIFIED_IN_INSTANCE varchar(6),
	CYCLE numeric(2,0),
	SUBCYCLE numeric(2,0),
	PRIMARY KEY (CN),
	UNIQUE(PLT_CN, CONDID, TREE)
);