-- Create the SOILS_LAB table
create table FIA.SOILS_LAB(
	CN varchar(34),
	PLT_CN varchar(34),
	INVYR numeric(4,0),
	STATECD numeric(4,0),
	COUNTYCD numeric(3,0),
	PLOT numeric(5,0),
	SMPLNNBR numeric(3,0),
	VSTNBR numeric(1,0),
	LAYER_TYPE varchar(10),
	SAMPLER_TYPE varchar(2),
	QASTATCD numeric(1,0),
	SAMPLE_DATE date,
	LAB_ID varchar(10),
	SAMPLE_ID varchar(12),
	FIELD_MOIST_SOIL_WT numeric(7,2),
	AIR_DRY_SOIL_WT numeric(7,2),
	OVEN_DRY_SOIL_WT numeric(7,2),
	FIELD_MOIST_WATER_CONTENT_PCT numeric(6,2),
	RESIDUAL_WATER_CONTENT_PCT numeric(6,2),
	TOTAL_WATER_CONTENT_PCT numeric(6,2),
	BULK_DENSITY numeric(7,3),
	COARSE_FRACTION_PCT numeric(7,3),
	C_ORG_PCT numeric(7,3),
	C_INORG_PCT numeric(7,3),
	C_TOTAL_PCT numeric(7,3),
	N_TOTAL_PCT numeric(7,3),
	PH_H2O numeric(7,3),
	PH_CACL2 numeric(7,3),
	EXCHNG_NA numeric(8,3),
	EXCHNG_K numeric(7,3),
	EXCHNG_MG numeric(8,3),
	EXCHNG_CA numeric(8,3),
	EXCHNG_AL numeric(7,3),
	ECEC numeric(7,3),
	EXCHNG_MN numeric(7,3),
	EXCHNG_FE numeric(7,3),
	EXCHNG_NI numeric(7,3),
	EXCHNG_CU numeric(7,3),
	EXCHNG_ZN numeric(7,3),
	EXCHNG_CD numeric(7,3),
	EXCHNG_PB numeric(7,3),
	EXCHNG_S numeric(8,3),
	BRAY1_P numeric(7,3),
	OLSEN_P numeric(7,3),
	MEASYEAR numeric(4,0),
	CREATED_BY varchar(30),
	CREATED_DATE date,
	CREATED_IN_INSTANCE varchar(6),
	MODIFIED_BY varchar(30),
	MODIFIED_DATE date,
	MODIFIED_IN_INSTANCE varchar(6),
	PRIMARY KEY (CN),
	UNIQUE(PLT_CN, SMPLNNBR, LAYER_TYPE)
);