-- Create the SUBPLOT table
create table FIA.SUBPLOT(
	CN varchar(34),
	PLT_CN varchar(34),
	PREV_SBP_CN	varchar(34),
	INVYR numeric(4,0),
	STATECD numeric(4,0),
	UNITCD numeric(2,0),
	COUNTYCD numeric(3,0),
	PLOT numeric(5,0),
	SUBP numeric(3,0),
	SUBP_STATUS_CD numeric(1,0),
	POINT_NONSAMPLE_REASN_CD numeric(2,0),
	MICRCOND numeric(1,0),
	SUBPCOND numeric(1,0),
	MACRCOND numeric(1,0),
	CONDLIST numeric(4,0),
	SLOPE numeric(3,0),
	ASPECT numeric(3,0),
	WATERDEP numeric(2,1),
	P2A_GRM_FLG varchar(1),
	CREATED_BY varchar(30),
	CREATED_DATE date,
	CREATED_IN_INSTANCE varchar(6),
	MODIFIED_BY varchar(30),
	MODIFIED_DATE date,
	MODIFIED_IN_INSTANCE varchar(6),
	CYCLE numeric(2,0),
	SUBCYCLE numeric(2,0),
	ROOT_DIS_SEV_CD_PNWRS numeric(1,0),
	NF_SUBP_STATUS_CD numeric(1,0),
	NF_SUBP_NONSAMPLE_REASN_CD numeric(2,0),
	P2VEG_SUBP_STATUS_CD numeric(1,0),
	P2VEG_SUBP_NONSAMPLE_REASN_CD numeric(2,0),	
	INVASIVE_SUBP_STATUS_CD numeric(1,0),
	INVASIVE_NONSAMPLE_REASN_CD numeric(2,0),
	PRIMARY KEY (CN),
	UNIQUE(PLT_CN, SUBP)
);