-- Create the TREE_REGIONAL_BIOMASS table
create table FIA.TREE_REGIONAL_BIOMASS(
	TRE_CN varchar(34),
	STATECD	numeric(4,0),
	REGIONAL_DRYBIOT numeric(13,6),
	REGIONAL_DRYBIOM numeric(13,6),
	CREATED_BY varchar(30),
	CREATED_DATE date,
	CREATED_IN_INSTANCE varchar(6),
	MODIFIED_BY varchar(30),
	MODIFIED_DATE date,
	MODIFIED_IN_INSTANCE varchar(6),
	PRIMARY KEY (TRE_CN)
);