-- Create the TREE_GRM_ESTN table
create table FIA.TREE_GRM_ESTN(
	CN varchar(34),
	STATECD smallint,
	INVYR numeric(4,0),
	PLT_CN varchar(34),
	TRE_CN varchar(34),
	LAND_BASIS varchar(10),
	ESTIMATE varchar(20),
	ESTN_TYPE varchar(10),
	ESTN_UNITS varchar(3),
	COMPONENT  varchar(15),
	SUBPTYP_GRM numeric(1,0),
	REMPER numeric(3,1),
	TPAGROW_UNADJ numeric(11,6),
	TPAREMV_UNADJ numeric(11,6),
	TPAMORT_UNADJ numeric(11,6),
	ANN_NET_GROWTH numeric(13,6),
	REMOVALS numeric(13,6),
	MORTALITY numeric(13,6),
	EST_BEGIN numeric(13,6),
	EST_BEGIN_RECALC varchar(1),
	EST_END numeric(13,6),
	EST_MIDPT numeric(13,6),
	EST_THRESHOLD numeric(13,6),
	DIA_BEGIN numeric(5,2),
	DIA_BEGIN_RECALC varchar(1),
	DIA_END  numeric(5,2),
	DIA_MIDPT numeric(5,2),
	DIA_THRESHOLD numeric(5,2),
	G_S  numeric(13,6),
	I numeric(13,6),
	G_I numeric(13,6),
	M numeric(13,6),
	G_M numeric(13,6),
	C numeric(13,6),
	G_C numeric(13,6),
	R numeric(13,6),
	G_R numeric(13,6),
	D numeric(13,6),
	G_D numeric(13,6),
	CD numeric(13,6),
	G_CD numeric(13,6),
	CI numeric(13,6),
	G_CI numeric(13,6),
	CREATED_BY varchar(30),
	CREATED_DATE date,
	CREATED_IN_INSTANCE varchar(6),
	MODIFIED_BY varchar(30),
	MODIFIED_DATE date,
	MODIFIED_IN_INSTANCE varchar(6),
	PRIMARY KEY (CN),
	UNIQUE(TRE_CN, LAND_BASIS, ESTIMATE,ESTN_TYPE, ESTN_UNITS)
);