-- Create the VEG_SUBPLOT_SPP table
create table FIA.VEG_SUBPLOT_SPP(
	CN varchar(34),
	PLT_CN varchar(34),
	VVT_CN varchar(34),
	VSB_CN varchar(34),
	VPS_CN varchar(34),
	INVYR numeric(4,0),
	STATECD numeric(4,0),
	COUNTYCD numeric(3,0),
	PLOT numeric(5,0),
	SUBP numeric(1,0),
	VEG_FLDSPCD varchar(16),
	UNIQUE_SP_NBR numeric(2,0),
	VEG_SPCD varchar(16),
	SP_CANOPY_COVER_TOTAL numeric(5,2),
	SP_CANOPY_COVER_LAYER_1_2 numeric(5,2),
	SP_CANOPY_COVER_LAYER_3 numeric(5,2),
	SP_CANOPY_COVER_LAYER_4 numeric(5,2),
	QUAD_1_PRESENCE numeric(1,0),
	QUAD_2_PRESENCE numeric(1,0),
	QUAD_3_PRESENCE numeric(1,0),
	DUMMY_SUBP_COVER_PRE2004 numeric(1,0),
	MAX_COVER_LAYER_NBR_PRE2004 numeric(1,0),
	CREATED_BY varchar(30),
	CREATED_DATE date,
	CREATED_IN_INSTANCE varchar(6),
	MODIFIED_BY varchar(30),
	MODIFIED_DATE date,
	MODIFIED_IN_INSTANCE varchar(6),
	PRIMARY KEY (CN),
	UNIQUE(PLT_CN, VVT_CN, VPS_CN, VSB_CN)
);	